version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-weather
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vio
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../.mongo_data:/data/db
